### ISSUE TITLE
Overwriting Metadata

### ISSUE THREAD

**Issue by lswith** [spandex-project/spandex_phoenix#15]
It seems that the `customize_metadata` function will override any of the current values that are set in the top_level span. 

The customize metadata should make sure to keep anything that has already been set.

**Comment by GregMefford** [comment]
I'm glad that you're (trying to) make use of this feature, sorry it didn't work the way you expected! :bowtie: 

I believe the problem is that you didn't make a call to the default implementation and then modify it, like we show as an example in the docs. The reason we don't set the defaults when you override is that perhaps the reason you're overriding is that the defaults are too computationally expensive for your particular application, so we want to leave that option up to you.

(from https://hexdocs.pm/spandex_phoenix/SpandexPhoenix.html):

```elixir
defmodule MyApp.Tracer do
  use Spandex.Tracer, otp_app: :my_app

  def customize_metadata(conn) do
    name = conn.path_params["name"] || ""

    conn
    |> SpandexPhoenix.default_metadata() # <--- Note the call to the default function
    |> Keyword.update(:resource, "", &String.replace(&1, ":name", name))
  end
end

defmodule MyAppWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :my_app
  use SpandexPhoenix, customize_metadata: &MyApp.Tracer.customize_metadata/1
  plug Router

end
```

**Comment by zachdaniel** [comment]
No response in a while, and the method of resolving the issue was described by @GregMefford, so I think this is good to go.
