### ISSUE TITLE
No way to disable spandex for phoenix

### ISSUE THREAD

**Issue by aleklisi** [spandex-project/spandex_phoenix#25]
There is no config option for disabling SpandexPhoenix even though normal spandex may be disabled eg for the test environment.

**Comment by aleklisi** [comment]
I tried filtering out all traces but it still does not work:
```elixir
use SpandexPhoenix, filter_traces: &__MODULE__.filter_traces/1

...


def filter_traces(_conn) do
    Application.get_env(:my_app, :mix_env) in [:test]
  end
```

**Comment by dnlserrano** [comment]
I agree it may be a bit counter-intuitive, but it seems to work [the other way around](https://github.com/spandex-project/spandex_phoenix/blob/e6ef99a3f1d20d51751a985986279a75440d2840/test/plug/start_trace_test.exs#L34). E.g.,

```elixir
  def filter_traces(_conn) do
    Mix.env() not in [:test]
  end
```

This will **_"filter in"_** (i.e., let through) only those that yield `true` for the filter. In this case, if your `MIX_ENV` is `test`, it will not trace it. Otherwise, it filters it in (i.e., it **will** trace it).

```elixir
  def filter_traces(_conn) do
    Mix.env() not in [:dev, :test]
  end
```

In this config we only ever trace if `MIX_ENV` is different than `dev` and different than `test`. E.g., in `prod`, we'd trace it!

**Comment by zachdaniel** [comment]
Correct, it works the same way that `Enum.filter/2` works. `Enum.filter/2` *keeps* elements that match the predicate, whereas `Enum.reject/2` keeps elements that *don't*. Closing as the question has been answered.

@aleklisi thank you for the question and @dnlserrano thank you for helping them :D
